common: &common_settings
  from_email: Configure your email <from@example.com>
  smtp_username: SMTP username
  smtp_password: SMTP password

production:
  <<: *common_settings
  host: Production hostname

development: &non_production_settings
  <<: *common_settings
  host: localhost:3000

test:
  <<: *non_production_settings